In [ ]:
기본 RNN

In [1]:
import tensorflow as tf
import numpy as np
#def reset_graph(seed=42):
#    reset_default_graph()
#    tf.set_random_seed(seed)
#    np.random.seed(seed)

#tf.reset_default_graph() #그래프 초기화 (변수 생성)
#
#n_inputs=3 #입력데이터
#n_neurons=5 #셀의 가중치 사이즈
#
#X0=tf.placeholder(tf.float32,[None,n_inputs]) #4x3 으로 들어옴
#X1=tf.placeholder(tf.float32,[None,n_inputs]) #4x3 으로 
#
##[0,1,2] 하나의 셀로 입력
##FFNN(말단 데이터 하나가)
##(num_units=n_neurons) :가중치 사이즈=>특성을 찾아내는 것
#basic_cell=tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)  #사이즈를 5개로 찾아내겠다
#
##static_rnn :rnn 네트워크 :4개의 셀이 연결되면서 메모리 확보
#output_seqs,states=tf.contrib.rnn.static_rnn(basic_cell,[X0,X1],dtype=tf.float32) #2 4 3  #2는 배치사이즈 x 셀 수 x 뉴런수
#Y0,Y1=output_seqs
#
##출력, 다음 셀로 연결되는 값:마지막 state값(수평으로 연결)
#init=tf.global_variables_initializer()
#X0_batch=np.array([0,1,2],[3,4,5],[6,7,8],[9,0,1])
#X1_batch=np.array([9,8,7],[0,0,0],[6,5,4],[3,2,1])


import numpy as np
import os
import tensorflow as tf

# def reset_graph(seed=42):
#     tf.reset_default_graph()
#     tf.set_random_seed(seed)
#     np.random.seed(seed)
tf.reset_default_graph() # 그래프 초기화(변수 생성)
n_inputs = 3 # 입력 데이터
n_neurons = 5 # 셀의 가중치 사이즈
X0 = tf.placeholder(tf.float32, [None, n_inputs]) # 4x3
X1 = tf.placeholder(tf.float32, [None, n_inputs]) # 4x3
# [0,1,2] 사이즈가 하나의 셀로 입력
# FFNN(Feed Forward Neural Network)
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
# static_rnn : RNN Network [4개의 셀이 연결되면서 메모리 확보]
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1], dtype=tf.float32) # 2x4x3 [배치 사이즈*셀 수*뉴런 수]
Y0, Y1 = output_seqs
init = tf.global_variables_initializer() # 출력, 다음 셀로 전달되는 값: 마지막 states 값(수평으로 셀을 연결)
X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch = np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [3]:
#with tf.Session() as sess:
#    init.run()
#    Y0_val,Y1_val=sess.run([Y0,Y1],feed_dict={X0:X0_batch,X1:X1_batch})
#print('처음 데이터 특성:',Y0_val,"차수:",Y0_val.shape)
#print('두번째데이터 특성:',Y1_val,"차수:",Y1_val.shape)
#
##4x3 =>4x5

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0,Y1], feed_dict={X0: X0_batch, X1: X1_batch})

print("처음 데이터 특성: ", Y0_val, "차수: ",Y0_val.shape)   # 4*5 : cell이 4개, 특징 5개
print("두번째 데이터 특성: ", Y1_val, "차수: ",Y1_val.shape) # 4*5
# 4*3 -> 4*5
# 셀이 가지고 있는 가중치 사이즈는? : 3*5 : 3개가 들어와서 5개로 나갔으니까..... : 4*3 -> 4*5에서 끝 부분들.. 3*5

처음 데이터 특성:  [[-0.93172103  0.8611625   0.4901676  -0.84947175 -0.38926083]
 [-0.99980164  0.996971    0.8299809  -0.8657474   0.854739  ]
 [-0.9999995   0.9999383   0.9507826  -0.88037705  0.99462146]
 [-0.4373169  -0.79141515  0.9937681   0.99993294  0.9998212 ]] 차수:  (4, 5)
두번째 데이터 특성:  [[-0.9999953   0.99992454  0.7928492   0.8861348   0.9998628 ]
 [ 0.2832867   0.73218375 -0.50428265  0.4349015  -0.5756295 ]
 [-0.9993412   0.9983429   0.13845792  0.92875814  0.99566257]
 [-0.9784409   0.04489376 -0.3344527   0.9089518   0.8869909 ]] 차수:  (4, 5)


In [4]:
#셀이 가지고 있는 가중치 사이즈는  3x 5

In [5]:
#def reset_graph(seed=42):
#    reset_default_graph()
#    tf.set_random_seed(seed)
#    np.random.seed(seed)
#
#tf.rest_default 
#n_steps=28
#n_inputs=28
#n_neurons=150
#n_outputs=10
#learning_rate=0.001
#
#X=tf.placeholder(tf.float32,[None,n_steps,n_inputs])
#Y=tf.placeholder(tf.int32,[None])
#
#basic_cell=tf.contrib.rnn.basicRNNCell(num_units=n_neurons)
#outputs,states=tf.nn.dynamic_rnn(basic_cell,X,dtype=tf.float32)
#logits=tf.layers.dense(states,n_outputs)
#xentropy=tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,logits=logits)
#
#loss=tf.reduce_mean(xentropy)
#optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate)
#training_op=optimizer.minimize(loss)
#
#correct=tf.nn.in_top.k(logits,y,1)
#accuracy=tf.reduce_mean(tf.cast(correct,tf.float32))
#init=tf.global_varables_initializer()


#이미지 784(28x28)
n_steps = 28 #셀수
n_inputs = 28  #셀당 인풋사이즈
n_nuerons = 150  #뉴런출력
n_outputs = 10  #확률 사이즈
learning_rate = 0.001

tf.reset_default_graph()
#3차원으로 
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

#FFNN 
#셀:27개
#states 마지막 셀의 수평으로 전달 되는 값
#states는 마지막 셀의 outputs 과 같다.
#28개의 셀이 있는데 마지막 1개의 ouput.을 사용한다=>many to one :감정분류 (분류기)
#states 의 차수:150x 150
#outputs :의 차수: latent time  지연시간을 통해 계산될 셀의 모든 값을 결합 출력 150 * 28 * 150

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype = tf.float32)

#150개의 특징중에 10개만 추출 
#dense 입력차수,출력차수만 지정하면 자동으로 바이어스를 만들고 가중치 공간을 확보해서 계산
#150 x 150 =>150 x 10 
#dense 의 가중치 사이즈= 150x10

logits = tf.layers.dense(states, n_outputs)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits) #분류를 위한 미분이 가능한 식으로 바뀜
loss = tf.reduce_mean(xentropy) #배치사이즈 를 쓰는 이유 =>평균을 통해 .loss 를 구함
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate) #AdamOptimizer :momentum +propgrad
training_op = optimizer.minimize(loss) 
correct = tf.nn.in_top_k(logits, y, 1)  #가장큰값
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))
init = tf.global_variables_initializer()

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Use keras.layers.dense instead.


In [48]:
cnn ,rnn  모두 ffnn 의 전 단계 (융합)

SyntaxError: invalid syntax (<ipython-input-48-b52a6ff471ea>, line 1)

In [6]:
from tensorflow.examples.tutorials.mnist import input_data
mnist=input_data.read_data_sets('/tmp/data/')
X_test=mnist.test.images.reshape((-1,n_steps,n_inputs))
Y_test=mnist.test.labels

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [7]:
n_epochs=100
batch_size=150
with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):  #60000 만개(테스트)의 데이터150으로 나누고 100씩 
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch=mnist.train.next_batch(batch_size)
            X_batch=X_batch.reshape((-1,n_steps,n_inputs))
            sess.run(training_op,feed_dict={X:X_batch,y:y_batch})
            acc_train=accuracy.eval(feed_dict={X:X_batch,y:y_batch})
            acc_test=accuracy.eval(feed_dict={X:X_batch,y:y_batch})
        print(epoch,"train accuracy:",acc_train,"test accuracy:",acc_test)

0 train accuracy: 0.36 test accuracy: 0.36
1 train accuracy: 0.38666666 test accuracy: 0.38666666
2 train accuracy: 0.44 test accuracy: 0.44
3 train accuracy: 0.50666666 test accuracy: 0.50666666
4 train accuracy: 0.46666667 test accuracy: 0.46666667
5 train accuracy: 0.50666666 test accuracy: 0.50666666
6 train accuracy: 0.49333334 test accuracy: 0.49333334
7 train accuracy: 0.5133333 test accuracy: 0.5133333
8 train accuracy: 0.5133333 test accuracy: 0.5133333
9 train accuracy: 0.56666666 test accuracy: 0.56666666
10 train accuracy: 0.52 test accuracy: 0.52
11 train accuracy: 0.58 test accuracy: 0.58
12 train accuracy: 0.50666666 test accuracy: 0.50666666
13 train accuracy: 0.48 test accuracy: 0.48
14 train accuracy: 0.54 test accuracy: 0.54
15 train accuracy: 0.53333336 test accuracy: 0.53333336
16 train accuracy: 0.5466667 test accuracy: 0.5466667
17 train accuracy: 0.5466667 test accuracy: 0.5466667
18 train accuracy: 0.53333336 test accuracy: 0.53333336
19 train accuracy: 0.53333

In [8]:
#BasicRNNCell :기본데이터가 입력
#MultiRNNCell :수직으로 레이어 구성
#dynamic_rnn : 
#3층 셀이 28개가 조성:고정사이즈
#reset_praph()
n_steps = 28 
n_inputs = 28  
n_nuerons = 150  
n_outputs = 10  
learning_rate = 0.001
tf.reset_default_graph()
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

n_neurons=100
n_layers=3  #3개의 멀티 레이어: 3개의 셀을 생성

layers=[tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,activation=tf.nn.relu) for layer in range(n_layers)]

#3개의 셀을 조합해서 MultiRNNCell을 만듦
multi_layer_cell=tf.contrib.rnn.MultiRNNCell(layers)

Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.


In [9]:
#dynamic_rnn :셀로 입력되는 데이터의 개수에 맞추어서 셀을 구성
#나는 학교에 간다. static_rnn 동일한 사이즈 :큰것 기준, 작은 것은 padding(자체도 데이터이기 때문에 dynamic_rnn를 씀)
#입력 사이즈 변동=가중치 조절 =>나가는 특징은 일치
outputs,states=tf.nn.dynamic_rnn(multi_layer_cell,X,dtype=tf.float32)

#states가 몇개 발생하는가? 3(멀티레이어)x 150x 100
states_concat=tf.concat(axis=1, values=states)  #150 x 300
logits=tf.layers.dense(states_concat,n_outputs)  #가중치: 300 X 10 , logit:150x 10 =확률값

xentropy=tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,logits=logits)
#softmax을 거치면서 원핫 인코딩 * log (예측값)
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate) #AdamOptimizer :momentum +propgrad
loss = tf.reduce_mean(xentropy)
training_op = optimizer.minimize(loss) 
correct = tf.nn.in_top_k(logits, y, 1)  #가장큰값
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))
init = tf.global_variables_initializer()

In [10]:
n_epochs=10
batch_size=150
with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):  #60000 만개(테스트)의 데이터150으로 나누고 100씩 
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch=mnist.train.next_batch(batch_size)
            X_batch=X_batch.reshape((-1,n_steps,n_inputs))
            sess.run(training_op,feed_dict={X:X_batch,y:y_batch})
            acc_train=accuracy.eval(feed_dict={X:X_batch,y:y_batch})
            acc_test=accuracy.eval(feed_dict={X:X_batch,y:y_batch})
        print(epoch,"train accuracy:",acc_train,"test accuracy:",acc_test)

0 train accuracy: 0.9533333 test accuracy: 0.9533333
1 train accuracy: 0.9533333 test accuracy: 0.9533333
2 train accuracy: 0.99333334 test accuracy: 0.99333334
3 train accuracy: 0.97333336 test accuracy: 0.97333336
4 train accuracy: 0.99333334 test accuracy: 0.99333334
5 train accuracy: 0.99333334 test accuracy: 0.99333334
6 train accuracy: 0.9866667 test accuracy: 0.9866667
7 train accuracy: 0.98 test accuracy: 0.98
8 train accuracy: 0.98 test accuracy: 0.98
9 train accuracy: 0.9866667 test accuracy: 0.9866667


In [35]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)
learning_rate = 0.001
total_epoch = 10
batch_size = 128
n_input =28
n_step = 28
n_hidden = 128
n_class = 10                          #세로   #가로
X = tf.placeholder(tf.float32, [None, n_step, n_input]) #128 X 28 x28
Y = tf.placeholder(tf.float32, [None, n_class]) #128 x10
W = tf.Variable(tf.random_normal([n_hidden, n_class])) #n_hidden : 노드(특징추출하는 레이어수) 128 x 10 (0~9 까지)
b = tf.Variable(tf.random_normal([n_class])) #10

#28 x 128 사이즈의 가중치
cell = tf.nn.rnn_cell.BasicRNNCell(n_hidden) #neurons :128특징 :n_hidden : 노드(특징추출하는 레이어수) 128 x 10 (0~9 까지)  

#cell 수: 28 
outputs, states = tf.nn.dynamic_rnn(cell, X, dtype = tf.float32)

#outputs: 128 x 28 x128 , states:128 x 128 
outputs = tf.transpose(outputs, [1,0,2])  #28x 128x 128 

#셀로 
outputs = outputs[-1]  #맨 마지막 셀 : ??
model = tf.matmul(outputs, W) + b
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = model, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./mnist/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [39]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
total_batch = int(mnist.train.num_examples/batch_size)
for epoch in range(total_epoch):
    total_cost =0
    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        #이미지 사이즈로 리쉐입
        batch_xs = batch_xs.reshape((batch_size, n_step, n_input))
        #python 이 계산한 마지막 결과가 저장되는 것이 _
        _, cost_val = sess.run([optimizer, cost], feed_dict = {X: batch_xs, Y: batch_ys})
        total_cost += cost_val
    print("Epoch: ", '%04d' % (epoch + 1), 'Avg. cost = ', '{:.3f}'.format(total_cost/total_batch))
print("최적화 완료")

Epoch:  0001 Avg. cost =  0.516
Epoch:  0002 Avg. cost =  0.241
Epoch:  0003 Avg. cost =  0.193
Epoch:  0004 Avg. cost =  0.153
Epoch:  0005 Avg. cost =  0.142
Epoch:  0006 Avg. cost =  0.131
Epoch:  0007 Avg. cost =  0.124
Epoch:  0008 Avg. cost =  0.118
Epoch:  0009 Avg. cost =  0.112
Epoch:  0010 Avg. cost =  0.099
최적화 완료


In [ ]:
#문제
1.테스트 데이터를 이용하여 테스트하는 회로를 구성하시오
2. 3개의 셀을 갖는 multi-layer cell 로 수정하시오

#3개의 셀로 멀티레이어 생성해도 output 은 하나의 셀일 경우와 동일
#state에서는 3개의 레이어 마다 생성


n_layers=3  #3개의 멀티 레이어: 3개의 셀을 생성
layers=[tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,activation=tf.nn.relu) for layer in range(n_layers)]
multi_layer_cell=tf.contrib.rnn.MultiRNNCell(layers)
outputs,states=tf.nn.dynamic_rnn(multi_layer_cell,X,dtype=tf.float32)
........#앞에서한 예제를 보면 됨


#with 없이 세션을 열었기 때문에 바로 코딩을 해도 돌아간다 (앞의 예제에서 했음)
is_correct=tf.equal(tf.argmax(model,1),tf.argmax(Y,1))
accuracy=tf.reduce_mean(tf.cast(is_correct,tf.float32))
test_batch_size=len(mnist.test.images)
test_xs=mnist.test.images.reshape(test_batch_size,n_step,n_input)
test_ys=mnist.test.labels
print('정확도:',sess.run(accuracy,feed_dict:{X:test_xs,Y:test_ys})) #정확도 :0.977

In [43]:
#질문 !!
import numpy as np
values231=np.array([[[1],[2],[3]],[[2],[3],[4]]])
print('입력데이터의 shape',values231.shape) #2x3x1
tf.reset_default_graph()
tf.values231=tf.constant(values231,dtype=tf.float32) 
#1 x 100  :가중치가 4개 이기때문 , 
#LSTMCell 4개를 학습해야하므로 

lstm_cell=tf.contrib.rnn.LSTMCell(num_units=100) #뉴론

#rnn 모델은 동일 :망과 망을 연결할때 (번역망 : 한글, 영어)
#ratent time: 지연시간
outputs,state=tf.nn.dynamic_rnn(cell=lstm_cell,dtype=tf.float32,inputs=tf.values231)
print(state.c.shape) #2 100   #??
print(state.h.shape)  #2 100

print('rnn 이 출력하는 outputs의 의미',outputs.shape)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_run,state_run=sess.run([outputs,state])

입력데이터의 shape (2, 3, 1)
rnn 이 출력하는 outputs의 의미 (2, 3, 100)


In [2]:
import tensorflow as tf   
import numpy as np
values=tf.constant(np.array([[[1],[2],[3]],[[2],[3],[4]]]), dtype=tf.float32)
print(values

<tf.Tensor 'Const:0' shape=(2, 3, 1) dtype=float32>

In [29]:
#질문!

import tensorflow as tf    
tf.reset_default_graph()
values=tf.constant(np.array([[[1],[2],[3]],[[2],[3],[4]]]), dtype=tf.float32)
lstm_cell_fw=tf.contrib.rnn.LSTMCell(100)  #??
lstm_cell_bw=tf.contrib.rnn.LSTMCell(100)
#Multi cell: 셀에서
#양방향 LSTM
(output_fw,output_bw),(output_state_fw,output_state_bw)=tf.nn.bidirectional_dynamic_rnn(cell_fw=lstm_cell_fw, cell_bw=lstm_cell_bw,
                                                                                       inputs=values,dtype=tf.float32)
print(output_fw.shape)
print(output_bw.shape)
print(values.shape)


(2, 3, 100)
(2, 3, 100)
(2, 3, 1)


In [36]:
#embedding 한다..고 함
import pprint  #데이터 형태대로 찍을수 있게 하는거
from tensorflow.python.framework import ops
ops.reset_default_graph()
pp=pprint.PrettyPrinter(indent=4)
sess=tf.InteractiveSession() 
h=[1,0,0,0] #단어를 원핫인코딩: 수치화 
e=[0,1,0,0]
l=[0,0,1,0]
o=[0,0,0,1]
#h=[1,0,0,0]
#e=[0,1,0,0]
#l=[0,0,1,0]
#l=[0,0,1,0]
#o=[0,0,0,1]

#변수공유를 위해 지정
with tf.variable_scope('five_sequences') as scope:
    hidden_size=2  #4개 에서 2개의 특징으로 벡터화 된다.
    cell=tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data=np.array([[h,e,l,l,o]],dtype=np.float32)
    print(x_data.shape) #1, 5, 4 =데이터가 한개를 3차원으로 만들어주려고 
    pp.pprint(x_data)
    #셀의 개수:5
    #셀당 입력데이터는4
    #셀당 가중치는 4 x 2
    outputs,states=tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())
    print(outputs.shape)  #1 5 2 
    print(states.shape)   # 1(데이터가 한개가 들어갔으니깐),  2  =>[[0.5307638, 0.6647075]]
    pp.pprint(states.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[-0.2296784 , -0.5557229 ],
        [ 0.25059763, -0.03292963],
        [ 0.2394907 , -0.20342518],
        [ 0.24244171, -0.29622963],
        [-0.07254155, -0.18487242]]], dtype=float32)
(1, 5, 2)
(1, 2)
array([[-0.07254155, -0.18487242]], dtype=float32)


In [61]:
tf.reset_default_graph()
char_arr=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
num_dic={n:i for i, n in enumerate(char_arr)}#숫자를 자동으로 만들어줌(인덱스처럼....생성,enumerate 사용시는 i, n 처럼 두개필요)
dic_len=len(num_dic) #26 개 

#a : 0, b:1 ... 글자에 해당되는 것을 숫자로 줌 
#rule base=>자동 툴 =>가중치만 이용
seq_data=['word','wood','deep','dive','cold','cool','load','love','kiss','kind']

#10x3 (세번째 음절 까지만 보므로)  
#10x1 =target

In [62]:
#26 x 26 행렬
#10000000000000000000000000000000  a가 0번 이므로 0이 1이 되는 것
#01000000000000000000000000000000  b가 1번 이므로 01이 되는 것
#00100000000000000000000000000000  c가 2번 이므로 001이 되는 것

def make_batch(seq_data): #자동으로 문자를 원핫인코딩
    input_batch=[]
    target_batch=[]
    for seq in seq_data: #첫번째로 word가 들어가고 
        input=[num_dic[n] for n in seq[:-1]]  #n 이 w=22번 /n 에 o=14, 마지막은 안함
        target=num_dic[seq[-1]] #d= 3
        input_batch.append(np.eye(dic_len)[input]) #eye 가 자동으로 행렬을 만들어주는 함수.. ex) 22번이 1이 되는것을 찾아서...
        target_batch.append(target)
    return input_batch,target_batch

#input 에는 

In [63]:
learning_rate=0.01
n_hidden=128 #가중치를 정하는데 도움을 주는 애
total_epoch=30 #30번이돌아감
n_step=3 #3번학습할거라서??
n_input=n_class=dic_len  #26 개 

X=tf.placeholder(tf.float32,[None,n_step,n_input]) #10 ,3, 26
Y=tf.placeholder(tf.int32,[None]) #10 ,26
#ffnn
W=tf.Variable(tf.random_normal([n_hidden,n_class])) #128 x 26
b=tf.Variable(tf.random_normal([n_class]))


In [64]:
cell1=tf.nn.rnn_cell.BasicLSTMCell(n_hidden) #특성을 128개로 
cell1=tf.nn.rnn_cell.DropoutWrapper(cell1,output_keep_prob=0.5,seed=10)
cell2=tf.nn.rnn_cell.BasicLSTMCell(n_hidden)

#2레이어로 구성된 멀티셀
multi_cell=tf.nn.rnn_cell.MultiRNNCell([cell1,cell2])
outputs,states=tf.nn.dynamic_rnn(multi_cell,X,dtype=tf.float32)  #??

#outputs 10 3 128
#states 10 128

In [65]:
outputs=tf.transpose(outputs,[1,0,2]) #3 10 128 
outputs=outputs[-1] #맨뒤의 셀뺌 10 128   
model=tf.matmul(outputs,W)+b #비선형회귀방식
#분류에서의 엔트로피
cost=tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=model,labels=Y))
optimizer=tf.train.AdamOptimizer(learning_rate).minimize(cost)


In [89]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
input_batch , target_batch = make_batch(seq_data) # 단어데이터

for epoch in range(total_epoch):
    _, loss = sess.run([optimizer, cost], feed_dict={X:input_batch, Y:target_batch})
    print('Epoch : %04d'%(epoch+1), 'cost = {:.6f}'.format(loss)) 

Epoch : 0001 cost = 4.553142
Epoch : 0002 cost = 3.413800
Epoch : 0003 cost = 1.858945
Epoch : 0004 cost = 1.903587
Epoch : 0005 cost = 0.831649
Epoch : 0006 cost = 1.625600
Epoch : 0007 cost = 0.990520
Epoch : 0008 cost = 0.775356
Epoch : 0009 cost = 0.500011
Epoch : 0010 cost = 0.731038
Epoch : 0011 cost = 0.483169
Epoch : 0012 cost = 0.282181
Epoch : 0013 cost = 0.283094
Epoch : 0014 cost = 0.459404
Epoch : 0015 cost = 0.326421
Epoch : 0016 cost = 0.209920
Epoch : 0017 cost = 0.171105
Epoch : 0018 cost = 0.145702
Epoch : 0019 cost = 0.210732
Epoch : 0020 cost = 0.162402
Epoch : 0021 cost = 0.048038
Epoch : 0022 cost = 0.113698
Epoch : 0023 cost = 0.065581
Epoch : 0024 cost = 0.128191
Epoch : 0025 cost = 0.070206
Epoch : 0026 cost = 0.031214
Epoch : 0027 cost = 0.042788
Epoch : 0028 cost = 0.054056
Epoch : 0029 cost = 0.026347
Epoch : 0030 cost = 0.026552


In [79]:
prediction=tf.cast(tf.argmax(model,1),tf.int32) #실수형을 정수형으로 
prediction_check=tf.equal(prediction,Y)
accuracy=tf.reduce_mean(tf.cast(prediction_check,tf.float32)) #int32 ,float32로 하면 계산안될때가있당
input_batch,target_batch=make_batch(seq_data)
predict,accuracy_val=sess.run([prediction,accuracy],feed_dict={X:input_batch, Y:target_batch})

In [80]:
#문제:predict 한 결과를 출력하고 accuracy를 출력하시오
#입력단어와 예측 결과를 나란히 출력해 보시오

In [84]:
print('예측된 결과 ', predict)
print('accuracy',accuracy_val)

predict_words=[]

#단어가 순서대로 입력,순서대로 예측
for idx, val in enumerate(seq_data):
    last_char=char_arr[predict[idx]]#인덱스가 단어 매핑
    predict_words.append(val[:3]+last_char) #세번째 음절까지 (마지막음절은 뺐음 왜?)
print('입력값:',[w[:3]+ ' ' for w in seq_data])
print('예측값:',predict_words)

예측된 결과  [ 3  3 15  4  3 11  3  4 18  3]
accuracy 1.0
입력값: ['wor ', 'woo ', 'dee ', 'div ', 'col ', 'coo ', 'loa ', 'lov ', 'kis ', 'kin ']
예측값: ['word', 'wood', 'deep', 'dive', 'cold', 'cool', 'load', 'love', 'kiss', 'kind']
