In [ ]:
import flask #웹서버기능5000번 port 로 service 

In [31]:
import matplotlib   #시각화 패키지
import numpy as np  #별칭 class 
print(np.__version__) #상위 오브젝트가 가진 속성
def pprint(arr): #ndarry :numpy 의 기본데이터타입
    print("type:{}".format(type(arr)))
    print("shape:{}.dimension:{}.dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data:\n",arr)
    #숫자의 디폴트는 int32
arr=[1.0,2.0,3.0] #리스트
a=np.array([1,2,3])#ndarray 생성함수(매개변수:리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,).dimension:1.dtype:int32
Array's Data:
 [1 2 3]


In [32]:
#인스턴스상태
a=np.array([0,1,2,3,4,5,6,7,8,9])#ndarray
print(id(a)) #주소값확인
print(a.size) #데이터개수
print(a.astype(np.float32)) #데이터타입.numpy 는 행중심, 동질적
print(a.dtype.itemsize*a.size) #전체 메모리 사이즈(바이트)
#literator fot in range=> list
a=np.arange(1000) #>ndarray
a

2437827975488
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [69]:
#ndarray 초기화 함수들
print(np.zeros((3,4))) #0
print(np.ones((2,3,4),dtype=np.int16))
print(np.full((2,2),7))
print(np.eye(4)) #대각행렬 ,identity 행렬에서 항등원 +,*
print(np.empty((4,2))) #=>쓰레기값,아무의미없는 값


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[4.24399158e-313 1.69759663e-313]
 [4.88059032e-313 2.33419537e-313]
 [4.45619116e-313 1.90979621e-313]
 [4.66839074e-313 2.12199579e-313]]


In [19]:
a=np.arange(0,100,10) #ndarray
indices=[1,5,-1] #list
print(indices)
b=a[indices] #list를 인덱스로 사용 0~90 까지 10씩 가는데 거기에서 1번 5번 -1(거꾸로)번 인덱스면 
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [14]:
a=np.arange(11,36) #1차원 np.array + range 의 기능을 합침
a.shape=(5,5) #정상 모양을 갖춘개수  R
print(a)
print(type(a))
print(a.dtype) #int32  여기서 쓰는 데이터타입
print(a.size)
print(a.shape) #차수(5,5)
print(a.ndim)#2차원
print(a.nbytes) #100바이트=25개 * (한개가)4바이트
print(a.strides) #(20,4) 다음열의 데이터는 몇바이트를 건너뛰어야 하는가  
                 #4*5 =20 다음행은 몇바이트를 건너 뛰어야 하는가 

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [108]:
#
arr=np.arange(10) #0~9
print(type(arr))
print(arr)
print(arr[5]   )
print(arr[5:8]) #마지막 불포함
arr[5:8]=12 #데이터 업데이트
print(arr[1:6]) #1:8 은 1 2 3 4 12 12 12

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [115]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d[0]) #행우선 :행
print(arr2d[0][2]) 
print(arr2d[0,2]) 
print(arr2d[:2]) #0,1행 처음부터
print()

print(arr2d[:2,1:]) #0~1행, 열1~끝 
print(arr2d[1:])
print()

print(arr2d[:,1:]) #0~끝행, 1열~끝
print(arr2d[1,:2])
print(arr2d[2,:1])
print()

arr2d[:2,:1]=0
arr2d[:2,:1]=0
print(arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]
[[4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]

[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [17]:
#실제 저장은 일렬로, 사람이 데이터를 다루는 것은 입체로 480바이트 8개 지나가면 다음 행,3면 4행 5열 
#행렬 연산에서 앞의 행렬의 열수와 뒤의 행수를 일치시켜야 행렬 곱이 가능
#행렬곱에서 행렬 앞뒤로 바꾸면 안된다.
print("스트라이드의 값",np.ones((3,4,5),dtype=np.float64).strides)

#단일 데이터 float :8바이트

스트라이드의 값 (160, 40, 8)


In [119]:
#문제
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 2면2행3열
print("첫면",arr3d[0]) #0번면
print("첫차원 첫행은=",arr3d[0][0])
print("첫면 첫행, 첫 요소는=",arr3d[0][0][0])
#8을 출력
arr3d[1][0][1]
#12를 출력
arr3d[1][1][2]

첫면 [[1 2 3]
 [4 5 6]]
첫차원 첫행은= [1 2 3]
첫면 첫행, 첫 요소는= 1


12

In [26]:
#백업이 안됨: 대입하면 같은 주소를 가리키기 때문에 
#대입 :주소를 복사
arr3d[0]=42
old_values=arr3d.copy() #값이 똑같이 복사된다.카피하게되면 원본,복사본 2개가 되는것
arr3d[0]=42
print("값의 변경후")
print(arr3d)
print("이전값으로 복귀")
arr3d=old_values
print(arr3d) #arr3d 다르다 old 랑 


값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전값으로 복귀
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
Z=np.arange(36) #1차원으로 생성
print(Z)
Z=Z.reshape((6,6)) #2차원 행렬로 생성
reshape2=Z.reshape((2,3,6)) #3차원 면,행,열로 생성
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [70]:
arr=np.arange(32).reshape((8,4))
print(arr)
print()
print(arr[[1,5,7,2]]) #행중심
print()
print(arr[[-1,-5,-7,-2]]) #거꾸로 인덱싱  
print()
print(arr[[1,5,7,2],[0,3,1,2]]) 
print()
#fancy 인덱싱 :위에 있는 인덱싱의 단점을 보완함
print(arr[[1,2,5,7]][:,[0,1,2,3]]) #1,2,5,7의 행들을 다시 함수로 만들고 0~3번의 순서를 준것
print()
print(arr[[1,5,7,2]][:,[0,3,1,2]])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 23 29 10]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [41]:
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10+j)
    arr.append(ad)
print(arr)
arr=np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [44]:
print("주황색",arr[[0,1,2,3,4],[1,2,3,4,5]]) 
print("빨강색",arr[[0,2,5],2])
print("하늘색",arr[3:6][:,[0,2,5]])

주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [46]:
print("빨강색",arr[:,2])
print("주황색",arr[0,[3,4]])
print("녹색",arr[[2,4]][:,[0,2,4]])
print("green=",arr[4:][:,[4,5]])

빨강색 [ 2 12 22 32 42 52]
주황색 [3 4]
녹색 [[20 22 24]
 [40 42 44]]
green= [[44 45]
 [54 55]]


In [51]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #4x3 4행 3열?
print(x)
v=np.array([1,0,1])
print("타일출력")
vv=np.tile(v,(4,1)) #v가 4행 1열로
print(vv)
y=x+vv #4x3 배열연산=>요소별 연산
print(y)
#배열연산:양쪽차원이 일치해야함
print(x+v) #4x3, 1x3 브로드캐스팅  4x3 ,4x1  가능 
x+3  #상수는 모든데이터에 가능

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [57]:
x=np.arange(6).reshape((3,2)) #0~5까지 3행2열
print(x)
#거듭제곱(행렬곱)
#x@x  #앞의 행렬 열수와 뒤의 행렬의 행수가 일치해야함 다시 생각!
#(3x2)(3x2) #에러가뜸
            
#전치행렬 :행과 열을 바꿔 줌 ,#전치해주면 (3x2)(2x3) 이된다
x@x.T  #3x3
#print(np.transpose(x)) 도 가능

[[0 1]
 [2 3]
 [4 5]]


array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [80]:
arr=np.arange(24).reshape((2,3,4)) #0,1,2
print(arr)
print()
print(arr.transpose((1,0,2))) #3면2행4열로 바뀜
print()
print(arr.transpose((0,2,1))) #2면4행3열로 바뀜

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [84]:
#Boolean indexing (True/False)   중요!!!
#문자열은 대소문자 구분
names=np.array(['Seoul','Daejun','chungju','seoul','chungju','Daejun','Daejun'])
data=np.random.randn(7,4) #7행 4열의 행렬을 랜덤하게
print(data)
print(names=='Seoul') #1.0,0,0,0,0,
print(data[names=='Seoul']) #0번행
print(data[names=='Seoul',2:])
print(data[names=='Seoul',3])
print(names !='Seoul')
print(~(names=='Seoul')) #위의 것과 같음 ~은 부정
mask=(names=='Seoul')|(names=='chungju') #또는 
print(mask) 
print(data[mask])  #3개가 true

[[-0.9121697   1.16132256 -0.43877227 -0.10462475]
 [-1.10741455 -1.12267444 -1.0095676  -0.30078964]
 [-0.94219495  1.68836668  0.50312493  0.45548756]
 [-2.39740691  2.28573997 -0.99060095  2.28066299]
 [ 0.07442856 -0.05549438 -0.30660044  0.79971847]
 [ 0.17461314 -0.1196969  -0.1720281  -0.81480566]
 [ 0.90038969 -0.08992046  0.57094184 -1.13394006]]
[ True False False False False False False]
[[-0.9121697   1.16132256 -0.43877227 -0.10462475]]
[[-0.43877227 -0.10462475]]
[-0.10462475]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[-0.9121697   1.16132256 -0.43877227 -0.10462475]
 [-0.94219495  1.68836668  0.50312493  0.45548756]
 [ 0.07442856 -0.05549438 -0.30660044  0.79971847]]


In [72]:
xarr=np.array([1.1,1.2,1.2,1.3,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
print(zip(xarr,yarr,cond)) #요소별로 데이터를 묶음.zip 고유포멧 그래서 아래처럼 list로 변환
print(list(zip(xarr,yarr,cond)))
result=[(x if c else y) for x,y,c in zip (xarr,yarr,cond)] #3항 연산자
print("result=",result)

result=np.where(cond,xarr,yarr) #조건이 참이면 xarr 조건이 거짓이면 yarr
print(result)
      
arr=np.random.randn(4,4) #4by 4
print(arr)
print(np.where(arr>0,2,-2)) #나온 요소들이 참인가, 참이면 2, 거짓이면 -2

[(1.1, 2.1, True), (1.2, 2.2, False), (1.2, 2.3, True), (1.3, 2.4, True), (1.5, 2.5, False)]
result= [1.1, 2.2, 1.2, 1.3, 2.5]
[1.1 2.2 1.2 1.3 2.5]
[[-0.13435685 -0.66776968 -1.20471517 -0.49170229]
 [ 0.12764318  0.01800417  0.9954842  -0.75614719]
 [ 0.99153487  0.02346459 -1.16450575  0.51963602]
 [-0.52748826 -0.1545296   0.27762049 -0.10873906]]
[[-2 -2 -2 -2]
 [ 2  2  2 -2]
 [ 2  2 -2  2]
 [-2 -2  2 -2]]


In [75]:
#문제 다음데이터를 이용하여 두개 다 참일 때는 0, cond1 이 참일때는 1, cond2가 참일때는 2 그 외일 때는
#3으로 처리하여 출력하도록 하시오
#0,1,2,3
#조건 4
#where 3
result=[]
cond1=np.array([1,0,1,1,0,0,1],dtype=bool)
cond2=np.array([0,1,1,1,0,1,1],dtype=bool)

result=np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2,3)))
print("3항 연산자",result)

result=1*(cond1&~cond2)+2*(cond2&~cond1)+3* ~(cond1 | cond2)
print("수식을 이용한",result)

3항 연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [82]:
x=np.arange(1,10001)
y=np.arange(10001,20001)
z=np.zeros_like(x)  #다른 행렬과 같은 사이즈로 초기화 zeros_like()라는 함수를 사용
for i in range(10000):
    z[i]=x[i]+y[i]

In [83]:
a=np.array([1,2,3,4])
b=np.array([4,2,2,4])
print(np.all(a==b)) #전체가 참일때 참
print(np.any(a==b)) #하나라도 참이면 참
print(np.exp(a)) #지수함수 (자연대수:2.172) 느닷없이 로그를 취할때는 값을 작게 만들려고

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
#선형대수:선형으로 해결하자 =>비선형도 잘게 나누면 선형 

In [85]:
#행렬의 종류
#-정방행렬:정사각형(행과 열수가 같은 행렬)
#-대칭행렬:우상단과 좌하단 같은것 
#-대각행렬:scale을 변화시키는 요소
#-단위행렬(identity):행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬
#-역행렬:행렬의 나눗셈을 위해 구해서 곱해지는 행렬(정방행렬만 가능)
#-특이행렬:역행렬이 없는 행렬
#-직교행렬:축의 정직교,각 축과는 내적이 0인행렬
#-정방행렬이면서 대칭행렬:공분산 행렬,상관계수행렬,거리행렬
#-공분산:두 수간의 관계, ((한수-평균)*(다른수-평균))/(n-1)
#-상관계수(표준화 -1~1 사이값):공분산/표준편차의 곱

In [87]:
import numpy as np
F1=np.array([[1,2],[3,4]]) #2x2
F2=np.array([[2,2],[2,2]]) #2x2
print(F1)
print(F2)
print(F1+F2) #요소끼리
print(F1*F2) 
print(F1@F2) 
#1,2   2,2   행렬곱도 내적 1x2+2x2=6 
#3,4   2,2                 3x2+4x2=14
#       2,2,1             차원확장 (곱해야할 요소가 3개로 늘어남)
#       2,2,1   

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [88]:
#방정식의 해
#2x1 + x2 -2x3=-3
#3x1 +      x3=5
#  x1+ x2 - x3=-2



In [89]:
A=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b=np.transpose(np.array([[-3,5,-2]])) #열로 전치
print(b)
x=np.linalg.solve(A,b)#A의 역행렬을 구해서 b와 곱해줌
print(x)


[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [90]:
np.dot(np.linalg.inv(A),b) #행렬곱  #inv가 역행렬구하는 함수

array([[ 1.],
       [-1.],
       [ 2.]])

In [92]:
np.linalg.inv(A)@b #왜 역행렬을 구해야 하는가? 행렬은 나눗셈이 없어서 역행렬 곱해서

array([[ 1.],
       [-1.],
       [ 2.]])

In [94]:
#검산
2*1 +(-1) -2*2

-3

In [96]:
a=np.array([0,1,0]) #x축
b=np.array([1,0,0]) #y 축
res=np.dot(a,b) #내적사이각 =직각 (내적이 0이므로)  #행렬의 곱
print(res)

0


In [100]:
print(np.linalg.norm(a)) #|a|:벡터의 크기 
print(np.linalg.norm(b)) 
print(np.linalg.norm(a)*np.linalg.norm(b))
rad=res/(np.linalg.norm(a)*np.linalg.norm(b)) #cos(theta)
print("cos theta",rad) 
print(np.arccos(rad)) #theta 값을 구함
print(np.degrees(np.arccos(rad))) #사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [102]:
x=np.array([[1,2],[3,4]])
y=np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))  #1.11022302e-16 도 0 

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [105]:
#다음 방정식의 해를 구하고 검산하시오
#x+y+z=6
#  2y+5z=-4
#2x+5y-z=27

A=np.array([[1,1,1],[0,2,5],[2,5,-1]])
print(A)
b=np.transpose(np.array([[6,-4,27]])) #열로 전치
print(b)
x=np.linalg.solve(A,b)#A의 역행렬을 구해서 b와 곱해줌
print(x)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]


In [ ]:
#검산 x=5,y=3,z=-2
5+3-2=6