In [3]:
import numpy as np
x=np.array([[2,4,6],[1,2,3],[0,5,8]])
print(x)
print(np.max(x,axis=0))

[[2 4 6]
 [1 2 3]
 [0 5 8]]
[2 5 8]


In [ ]:
matplotlib inline
import malearn
import matplot.pyplot as plt
mglearn.plots.plot_scaling()

In [2]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[1,   np.nan,  2],
               [2,      3,      5],
               [np.nan,  4,     6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [3]:
df.dropna()

0    1  2
1  2.0  3.0  5

0    1  2
1  2.0  3.0  5

In [4]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [5]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6