In [ ]:
mlp(다중퍼셉트론)

In [4]:
from IPython.display import Image
import tensorflow as tf

In [5]:
from tensorflow import keras

In [6]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


In [7]:
x_val=x_train[50000:60000]
x_train=x_train[0:50000]
y_val=y_train[50000:60000]
y_train=y_train[0:50000]

In [8]:
print(x_train.shape)

(50000, 28, 28)


In [9]:
print(x_train.shape[0])

50000


In [14]:
print('train data has'+str(x_train.shape[0])+'samples')
print('every train data is ' + str(x_train.shape[1])+"*"+str(x_train.shape[2])+'image')

train data has50000samples
every train data is 28*28image


In [16]:
print('validation data has'+str(x_val.shape[0])+'samples')
print('every train data is '+str(x_val.shape[1])+'*'+str(x_train.shape[2])+'image')

validation data has10000samples
every train data is 28*28image


In [17]:
print(x_train[0][8])

[  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241
   0   0   0   0   0   0   0   0   0   0]


In [18]:
print(y_train[0:9])

[5 0 4 1 9 2 1 3 1]


In [ ]:
x_train=np.reshape

In [20]:
#넘파이사용해서 
x_train=x_train.reshape(50000,784)
x_val=x_val.reshape(10000,784)
x_test=x_test.reshape(10000,784)

print(x_train.shape)
print(x_test.shape)

(50000, 784)
(10000, 784)


In [21]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [22]:
#정규화:255로 나눠줌
x_train=x_train.astype('float32')
x_val=x_val.astype('float32')
x_test=x_test.astype('float32') 

gray_scale=255
x_train /=gray_scale
x_val /=gray_scale
x_test /=gray_scale



In [23]:
print(x_train[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [26]:
#원핫인코딩:
num_classes=10
y_train=tf.keras.utils.to_categorical(y_train,num_classes)
y_val=tf.keras.utils.to_categorical(y_val,num_classes)
y_test=tf.keras.utils.to_categorical(y_val,num_classes)

In [27]:
y_train

array([[[[0., 1., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         ...,
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.]],

        [[0., 1., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         ...,
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.]],

        [[0., 1., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         ...,
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 1., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         ...,
         [1., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
    

In [28]:
x=tf.placeholder(tf.float32,[None,784])
y=tf.placeholder(tf.float32,[None,10])

In [35]:
def mlp(x):
    # hidden layer1
    w1 = tf.Variable(tf.random_uniform([784,256]))
    b1 = tf.Variable(tf.zeros([256]))
    h1 = tf.nn.relu(tf.matmul(x, w1) + b1)
    # hidden layer2
    w2 = tf.Variable(tf.random_uniform([256,128]))
    b2 = tf.Variable(tf.zeros([128]))
    h2 = tf.nn.relu(tf.matmul(h1, w2) + b2)
    # output layer
    w3 = tf.Variable(tf.random_uniform([128,10]))
    b3 = tf.Variable(tf.zeros([10]))
    logits= tf.matmul(h2, w3) + b3
    
    return logits

In [36]:
logits=mlp(x)

In [38]:
loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=y))
train_op=tf.train.AdamOptimizer(learning_rate=0.01).minimize(loss_op)

In [ ]:
#그래프 돌리기
init=tf.global_variables_initializer()
epoch_cnt=30
batch_size=1000
iteration=len(x_train)//batch_size


In [ ]:
# with tf.Session() as sess:
    sess.run(init)
    for epoch in range(epoch_cnt):
        avg_loss=0.
        start=0
        end=batch_size
        
        for i in range(iteration):
            _,loss=sess.run([train_op,loss_op],
                           feed_dict={x:x_train[start:end],y:y_train[start:end]})
            start +=batch_size
            end +=batch_size
            avg_loss +=loss/iteration
            
        preds=tf.nn.sotfmax(logits)
        correct_prediction=tf.equal(tf.agrmax(preds,1),tf.argmax(y,1))
        accuracy=tf.reduce_mean(tf.cast(correct_prediction,'float'))
        cur_val_acc=accuracy.eval({x:x_val,y:y_val})
        print('epoch:' +str(epoch)+ ',validation accuracy:' +str(cur_val_acc)+ ',loss:'+ str(avg_loss))
      
    preds=tf.nn.softmax(logits)
    correct_prediction=tf.equal(tf.argmax(preds,1),tf.argmax(y,1))
    accuracy=tf.reduce_mean(tf.cast(correct_prediction,))
    print('[test accuracy]: ',accuracy.eval({x:x_test,y:y_test}))

In [ ]:
#책 

In [ ]:
기본rnn

In [4]:
import tensorflow as tf
import numpy as np
n_inputs=3
n_neurons=5

X0=tf.placeholder(tf.float32,[None,n_inputs])
X1=tf.placeholder(tf.float32,[None,n_inputs])

Wx=tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
Wy=tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
b=tf.Variable(tf.zeros([1,n_neurons],dtype=tf.float32))

Y0=tf.tanh(tf.matmul(X0,Wx)+b)
Y1=tf.tanh(tf.matmul(Y0,Wy)+tf.matmul(X1,Wx)+b)

init=tf.global_variables_initializer()

In [ ]:
import numpy as np
X0_batch=np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch=np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])

with tf.Session() as sess:
    init.run()
    Y0_val,Y1_val=sess.run([Y0,Y1],feed_dect={X0:X0_batch, X1:x1_batch})
    

In [ ]:
#static

In [ ]:
X0=tf.placeholder(tf.float32,[None,n_inputs])
X1=tf.placeholder(tf.float32,[None,n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
outputs, states = tf.nn.static_rnn(basic_cell, [X0,X1], dtype = tf.float32)

Y0,Y1=output_seqs

In [ ]:
#dynamic 

In [ ]:
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])


basic_cell = tf.contrib.rnn.BasicRNNCell(num_units = n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype = tf.float32)


In [ ]:
seq_length=tf.placeholder(tf.int32,[None])
outputs,states=tf.nn.dynamic_rnn(basic_cell,X,dtype=tf.float32,sequence_length=seq_length)

In [8]:
sess = tf.Session()
c = tf.constant([[1, 2], [3, 4], [5, 6]])
print(c)
print(sess.run(c))

Tensor("Const_3:0", shape=(3, 2), dtype=int32)
[[1 2]
 [3 4]
 [5 6]]


In [15]:
sess=tf.Session()
values=tf.constant(np.array([[[1],[2],[3]],[[2],[3],[4]]]), dtype=tf.float32)
print(sess.run(values))



[[[1.]
  [2.]
  [3.]]

 [[2.]
  [3.]
  [4.]]]


In [16]:
sess=tf.Session()
values231=np.array([[[1],[2],[3]],[[2],[3],[4]]])
print(sess.run(values231))

TypeError: Fetch argument array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]]) has invalid type <class 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)